# Generated by Django 2.0.5 on 2019-02-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('author', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=9)),
                ('location', models.URLField()),
                ('is_single', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts',
                                                 to='Messages.Collection')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part',
                                                 to='Messages.Message')),
            ],
        ),
    ]
