# Generated by Django 2.0.5 on 2019-07-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_auto_20190304_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thumbnail_url',
            field=models.URLField(default='http://imgurr.com'),
            preserve_default=False,
        ),
    ]
