# Generated by Django 2.0.5 on 2019-07-27 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_message_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='time_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
