# Generated by Django 2.0.5 on 2019-07-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0006_auto_20190727_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='part',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='album_name',
            field=models.CharField(default='', max_length=100, verbose_name='Album Name'),
        ),
        migrations.AddField(
            model_name='message',
            name='download_location',
            field=models.URLField(default='http://www.google.com'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
